# https://sw.kovidgoyal.net/kitty/conf/

# Theme
include tokyonight_night.conf
background #181320

# Font
include jetbrains_mono.conf
font_size 14.0

# Cursor
cursor #ffc777
cursor_beam_thickness 3
cursor_trail 3

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2
tab_activity_symbol "⭐ "

# Key Bindings

## Tabs
map cmd+opt+left previous_tab
map cmd+opt+right next_tab

